#!/bin/bash

APT_GET="apt-get -q -y --force-yes"
WGET="wget -m --no-check-certificate"
DATE=`date +"%Y%m%d%H%M%S"`
LOG_FILE="/tmp/postinstall-$DATE.log"

LISTE="curl openvpn whois vim"
SOURCES_LIST="https://raw.githubusercontent.com/hotfix/pve-postinstall/master/sources.list"
BASHRC_FILE="https://raw.githubusercontent.com/hotfix/debian-postinstall/master/.bashrc"

displaytitle() {
  displaymessage "------------------------------------------------------------------------------"
  displaymessage "$*"
  displaymessage "------------------------------------------------------------------------------"

}

displayerror() {
  displaymessage "$*" >&2
}

# Premier parametre: ERROR CODE
# Second parametre: MESSAGE
displayerrorandexit() {
  local exitcode=$1
  shift
  displayerror "$*"
  exit $exitcode
}

# Premier parametre: MESSAGE
# Autres parametres: COMMAND
displayandexec() {
  local message=$1
  echo -n "[En cours] $message"
  shift
  echo ">>> $*" >> $LOG_FILE 2>&1
  sh -c "$*" >> $LOG_FILE 2>&1
  local ret=$?
  if [ $ret -ne 0 ]; then
    echo -e "\r\e[0;31m   [ERROR]\e[0m $message"
  else
    echo -e "\r\e[0;32m      [OK]\e[0m $message"
  fi
  return $ret
}

displaytitle "-- Téléchargement du fichier sources.list
-- $SOURCES_LIST"
displayandexec "Archivage du fichier sources.list actuel" cp /etc/apt/sources.list /etc/apt/sources.list-orginal
displayandexec "Téléchargement du nouveau fichier sources.list" $WGET -O /etc/apt/sources.list $SOURCES_LIST

displaytitle "-- Mise à jour du système"
displayandexec "Mise à jour de la liste des dépots" $APT_GET update
displayandexec "Mise à jour des logiciels" $APT_GET upgrade

displaytitle "-- Installation des logiciels suivants: $LISTE"
displayandexec "Installation des logiciels" $APT_GET install $LISTE

displaytitle "-- Config minimal"
displayandexec "Config modprobe dummy" echo "options dummy numdummies=2" > /etc/modprobe.d/dummy.conf
displayandexec "Activate modprobe dummy" modprobe dummy

displayandexec "Archivage du fichier .bashrc actuel" cp /etc/apt/sources.list /etc/apt/sources.list-orginal
displayandexec "Téléchargement du nouveau fichier .bashrc" $WGET -O /root/.bashrc $BASHRC_FILE

displayandexec "Archivage du fichier bootlogd actuel" cp /etc/default/bootlogd /etc/default/bootlogd.original
displayandexec "Ajout d'une option dans bootlogd" echo "BOOTLOGD_ENABLE=Yes" >> /etc/default/bootlogd
